{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "response = requests.get(\"https://www.bbc.com/\")\n",
    "doc = BeautifulSoup(response.text, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----\n",
      "{'title': 'UN in aid plea after staff accused of Israel attack', 'href': '/news/world-middle-east-68119268', 'tag': 'Middle East', 'summary': 'Countries pause funding for UNRWA over Israeli allegations its staff were involved in the Hamas attacks.'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Protesters throw soup at Mona Lisa painting', 'href': '/news/world-europe-68121654', 'tag': 'Europe'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': \"World's largest cruise ship sets sail from Miami\", 'href': '/news/world-us-canada-68118822', 'tag': 'US & Canada'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': \"Stokes hails 'greatest win' - reaction after England topple India\", 'href': '/sport/live/cricket/67780959', 'tag': 'Cricket'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'BBC confronts man who abused boy in secretive Christian Church', 'href': '/news/world-us-canada-66449988', 'tag': 'US & Canada'}\n",
      "----\n",
      "{'title': 'Ukraine says it has uncovered major arms corruption', 'href': '/news/world-europe-68120973', 'tag': 'Europe', 'summary': \"Ukraine's security service accuses senior officials of trying to steal about $40m in an order for mortar shells.\"}\n",
      "----\n",
      "{'title': 'Who invented butter chicken? Creamy dish centre of court battle', 'href': '/news/world-asia-india-68053470', 'tag': 'India', 'summary': 'Butter chicken - a curry popular around the world - is now in the middle of a court battle in India.'}\n",
      "----\n",
      "{'title': 'Australian drill rap vs the police', 'href': '/news/world-australia-67364463', 'tag': 'Australia', 'summary': 'A standoff between a hip-hop act and law enforcement is fuelling a debate over art and censorship.'}\n",
      "----\n",
      "{'title': 'Australian Open: Sinner beats Medvedev to win first Grand Slam title', 'href': '/sport/live/tennis/67779985', 'tag': 'Tennis', 'summary': \"Jannik Sinner beats Daniil Medvedev in the Australian Open men's singles final in Melbourne - follow radio and text commentary.\"}\n",
      "----\n",
      "{'title': 'FA Cup: Superb Neto opener gives Wolves lead at West Brom', 'href': '/sport/live/football/68026390', 'tag': 'Football', 'summary': 'Follow radio commentary and live text coverage of four FA Cup games, including Newport v Man Utd on BBC One.'}\n",
      "----\n",
      "{'title': 'James edges out Curry as Lakers beat Warriors', 'href': '/sport/basketball/68121154', 'tag': 'Basketball', 'summary': 'LeBron James helps the Los Angeles Lakers to a thrilling 145-144 win over the Golden State Warriors as he secures the bragging rights over Steph Curry.'}\n",
      "----\n",
      "Couldn't find a tag!\n",
      "Couldn't find a summary\n",
      "{'title': 'The last male of an extinct species', 'href': '/future/article/20240124-the-photo-of-sudan-the-last-male-northern-white-rhino'}\n",
      "----\n",
      "Couldn't find a tag!\n",
      "Couldn't find a summary\n",
      "{'title': 'The cities cutting back on cars', 'href': '/future/article/20240122-from-london-to-new-york-can-quitting-cars-be-popular'}\n",
      "----\n",
      "Couldn't find a tag!\n",
      "Couldn't find a summary\n",
      "{'title': \"The plastic oceans we can't see\", 'href': '/future/article/20240115-visualising-the-great-pacific-garbage-patch'}\n",
      "----\n",
      "{'title': \"One of modern music's greatest enigmas\", 'href': 'https://www.bbc.com/culture/article/20240126-william-onyeabor-one-of-modern-musics-greatest-enigmas', 'tag': 'Culture', 'summary': 'How the elusive figure William Onyeabor became a cult icon'}\n",
      "----\n",
      "{'title': \"The curious ancient beginnings of 'bed culture'\", 'href': 'https://www.bbc.com/future/article/20240126-sleep-tight-a-curious-history-of-beds-through-the-centuries', 'tag': 'Future', 'summary': 'The ancient Romans had a different kind of bed for every activity.'}\n",
      "----\n",
      "{'title': \"Is this curry's lighter cousin?\", 'href': 'https://www.bbc.com/travel/article/20240126-kerala-ishtu-creamy-vegetable-stew', 'tag': 'Travel', 'summary': 'This creamy and mild vegetarian dish a variation on the English word \"stew\"'}\n",
      "----\n",
      "{'title': 'When employers gut middle managers, everyone hurts', 'href': 'https://www.bbc.com/worklife/article/20240126-mass-layoffs-often-hit-middle-managers-the-cuts-are-largel-short-sighted', 'tag': 'Worklife', 'summary': \"Companies are laying off experienced workers – it's often short-sighted\"}\n",
      "----\n",
      "{'title': \"Your pictures on the theme of 'wilderness'\", 'href': 'https://www.bbc.com/news/in-pictures-68082104', 'tag': 'In Pictures', 'summary': 'A selection of striking images from our readers around the world'}\n",
      "----\n",
      "{'title': 'Beauty giant Avon under fire over Russia links', 'href': 'https://www.bbc.com/news/business-67425366', 'tag': 'Business', 'summary': 'The firm is facing criticism for continuing production in Russia'}\n",
      "----\n",
      "{'title': 'The Traitors TV final reaches dramatic conclusion', 'href': 'https://www.bbc.com/news/entertainment-arts-68088493', 'tag': 'Entertainment & Arts', 'summary': 'Viewers found out in the final whether the traitors or the faithful had won the £95,000 prize'}\n",
      "----\n",
      "Couldn't find a tag!\n",
      "Couldn't find a summary\n",
      "{'title': 'See what your brain does when you look at art', 'href': '/reel/video/p0h6str5/see-what-your-brain-does-when-you-look-at-art'}\n",
      "----\n",
      "Couldn't find a tag!\n",
      "Couldn't find a summary\n",
      "{'title': 'Why this US state abolished the death penalty first', 'href': '/reel/video/p0h74jzx/why-this-us-state-abolished-the-death-penalty-first'}\n",
      "----\n",
      "Couldn't find a tag!\n",
      "Couldn't find a summary\n",
      "{'title': 'The secrets hidden in a reindeer brain', 'href': '/reel/video/p0h3t508/the-secrets-hidden-in-a-reindeer-brain'}\n",
      "----\n",
      "{'title': \"Auschwitz film was 'like Big Brother' in house next to camp\", 'href': '/news/entertainment-arts-68016298', 'tag': 'Entertainment & Arts', 'summary': 'For The Zone of Interest, hidden crews filmed fictional family life in a house next to the Nazi...'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Woodpeckers and sparrowhawks: Your Birdwatch 2024 pictures', 'href': '/news/science-environment-68106504', 'tag': 'Science & Environment'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': \"Meta tool to block nude images in teens' chats\", 'href': '/news/technology-68093343', 'tag': 'Technology'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Alarming 45-fold rise in measles in Europe - WHO', 'href': '/news/health-68068226', 'tag': 'Health'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Morrissey being treated for physical exhaustion', 'href': '/news/entertainment-arts-68121824', 'tag': 'Entertainment & Arts'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': \"Mars crash ends Nasa helicopter Ingenuity's mission\", 'href': '/news/science-environment-68099672', 'tag': 'Science & Environment'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Golden age or dying days for British theatre?', 'href': '/news/entertainment-arts-68040691', 'tag': 'Entertainment & Arts'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Women take the lead in India’s Republic Day parade', 'href': '/news/world-asia-india-68091821', 'tag': 'India'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': \"Bathers, wavers and semi-quavers: Africa's top shots\", 'href': '/news/world-africa-68091775', 'tag': 'Africa'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Rolling Tuscan fields among stunning travel award photos', 'href': '/news/in-pictures-68021767', 'tag': 'In Pictures'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': \"Football fever and giant cake: Africa's top shots\", 'href': '/news/world-africa-67986204', 'tag': 'Africa'}\n",
      "----\n",
      "Couldn't find a summary\n",
      "{'title': 'Snowy scenes from around the UK', 'href': '/weather/features/68006585', 'tag': 'Features'}\n"
     ]
    }
   ],
   "source": [
    "# find everything with the class of media-list__item\n",
    "# each one of these is going to be a row\n",
    "stories = doc.select('.media-list__item')\n",
    "\n",
    "# Starting off without ANY rows\n",
    "rows = []\n",
    "\n",
    "for story in stories:\n",
    "    print(\"----\")\n",
    "    # Starting off knowing NONE of the columns of data for this datapoint?\n",
    "    row = {}\n",
    "\n",
    "    row['title'] = story.select_one('h3').text.strip()\n",
    "\n",
    "    try:\n",
    "        # Find me a media__link OR a reel_link\n",
    "        row['href'] = story.select_one('.media__link, .reel__link')['href']\n",
    "    except:\n",
    "        print(\"Couldn't find a link\")\n",
    "\n",
    "    try:\n",
    "        row['tag'] = story.select_one('.media__tag').text.strip()\n",
    "    except:\n",
    "        print(\"Couldn't find a tag!\")\n",
    "\n",
    "    try:\n",
    "        row['summary'] = story.select_one('.media__summary').text.strip()\n",
    "    except:\n",
    "        print(\"Couldn't find a summary\")\n",
    "\n",
    "    print(row)\n",
    "    # When we're done adding info to our row, we're going to add it into our list\n",
    "    # of rows\n",
    "    rows.append(row)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>href</th>\n",
       "      <th>tag</th>\n",
       "      <th>summary</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>UN in aid plea after staff accused of Israel a...</td>\n",
       "      <td>/news/world-middle-east-68119268</td>\n",
       "      <td>Middle East</td>\n",
       "      <td>Countries pause funding for UNRWA over Israeli...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Protesters throw soup at Mona Lisa painting</td>\n",
       "      <td>/news/world-europe-68121654</td>\n",
       "      <td>Europe</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>World's largest cruise ship sets sail from Miami</td>\n",
       "      <td>/news/world-us-canada-68118822</td>\n",
       "      <td>US &amp; Canada</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Stokes hails 'greatest win' - reaction after E...</td>\n",
       "      <td>/sport/live/cricket/67780959</td>\n",
       "      <td>Cricket</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>BBC confronts man who abused boy in secretive ...</td>\n",
       "      <td>/news/world-us-canada-66449988</td>\n",
       "      <td>US &amp; Canada</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Ukraine says it has uncovered major arms corru...</td>\n",
       "      <td>/news/world-europe-68120973</td>\n",
       "      <td>Europe</td>\n",
       "      <td>Ukraine's security service accuses senior offi...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Who invented butter chicken? Creamy dish centr...</td>\n",
       "      <td>/news/world-asia-india-68053470</td>\n",
       "      <td>India</td>\n",
       "      <td>Butter chicken - a curry popular around the wo...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Australian drill rap vs the police</td>\n",
       "      <td>/news/world-australia-67364463</td>\n",
       "      <td>Australia</td>\n",
       "      <td>A standoff between a hip-hop act and law enfor...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Australian Open: Sinner beats Medvedev to win ...</td>\n",
       "      <td>/sport/live/tennis/67779985</td>\n",
       "      <td>Tennis</td>\n",
       "      <td>Jannik Sinner beats Daniil Medvedev in the Aus...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>FA Cup: Superb Neto opener gives Wolves lead a...</td>\n",
       "      <td>/sport/live/football/68026390</td>\n",
       "      <td>Football</td>\n",
       "      <td>Follow radio commentary and live text coverage...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>James edges out Curry as Lakers beat Warriors</td>\n",
       "      <td>/sport/basketball/68121154</td>\n",
       "      <td>Basketball</td>\n",
       "      <td>LeBron James helps the Los Angeles Lakers to a...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>The last male of an extinct species</td>\n",
       "      <td>/future/article/20240124-the-photo-of-sudan-th...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>The cities cutting back on cars</td>\n",
       "      <td>/future/article/20240122-from-london-to-new-yo...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>The plastic oceans we can't see</td>\n",
       "      <td>/future/article/20240115-visualising-the-great...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>One of modern music's greatest enigmas</td>\n",
       "      <td>https://www.bbc.com/culture/article/20240126-w...</td>\n",
       "      <td>Culture</td>\n",
       "      <td>How the elusive figure William Onyeabor became...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>The curious ancient beginnings of 'bed culture'</td>\n",
       "      <td>https://www.bbc.com/future/article/20240126-sl...</td>\n",
       "      <td>Future</td>\n",
       "      <td>The ancient Romans had a different kind of bed...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Is this curry's lighter cousin?</td>\n",
       "      <td>https://www.bbc.com/travel/article/20240126-ke...</td>\n",
       "      <td>Travel</td>\n",
       "      <td>This creamy and mild vegetarian dish a variati...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>When employers gut middle managers, everyone h...</td>\n",
       "      <td>https://www.bbc.com/worklife/article/20240126-...</td>\n",
       "      <td>Worklife</td>\n",
       "      <td>Companies are laying off experienced workers –...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Your pictures on the theme of 'wilderness'</td>\n",
       "      <td>https://www.bbc.com/news/in-pictures-68082104</td>\n",
       "      <td>In Pictures</td>\n",
       "      <td>A selection of striking images from our reader...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Beauty giant Avon under fire over Russia links</td>\n",
       "      <td>https://www.bbc.com/news/business-67425366</td>\n",
       "      <td>Business</td>\n",
       "      <td>The firm is facing criticism for continuing pr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>The Traitors TV final reaches dramatic conclusion</td>\n",
       "      <td>https://www.bbc.com/news/entertainment-arts-68...</td>\n",
       "      <td>Entertainment &amp; Arts</td>\n",
       "      <td>Viewers found out in the final whether the tra...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>See what your brain does when you look at art</td>\n",
       "      <td>/reel/video/p0h6str5/see-what-your-brain-does-...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Why this US state abolished the death penalty ...</td>\n",
       "      <td>/reel/video/p0h74jzx/why-this-us-state-abolish...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>The secrets hidden in a reindeer brain</td>\n",
       "      <td>/reel/video/p0h3t508/the-secrets-hidden-in-a-r...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Auschwitz film was 'like Big Brother' in house...</td>\n",
       "      <td>/news/entertainment-arts-68016298</td>\n",
       "      <td>Entertainment &amp; Arts</td>\n",
       "      <td>For The Zone of Interest, hidden crews filmed ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Woodpeckers and sparrowhawks: Your Birdwatch 2...</td>\n",
       "      <td>/news/science-environment-68106504</td>\n",
       "      <td>Science &amp; Environment</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Meta tool to block nude images in teens' chats</td>\n",
       "      <td>/news/technology-68093343</td>\n",
       "      <td>Technology</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Alarming 45-fold rise in measles in Europe - WHO</td>\n",
       "      <td>/news/health-68068226</td>\n",
       "      <td>Health</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Morrissey being treated for physical exhaustion</td>\n",
       "      <td>/news/entertainment-arts-68121824</td>\n",
       "      <td>Entertainment &amp; Arts</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>Mars crash ends Nasa helicopter Ingenuity's mi...</td>\n",
       "      <td>/news/science-environment-68099672</td>\n",
       "      <td>Science &amp; Environment</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>Golden age or dying days for British theatre?</td>\n",
       "      <td>/news/entertainment-arts-68040691</td>\n",
       "      <td>Entertainment &amp; Arts</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>Women take the lead in India’s Republic Day pa...</td>\n",
       "      <td>/news/world-asia-india-68091821</td>\n",
       "      <td>India</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>Bathers, wavers and semi-quavers: Africa's top...</td>\n",
       "      <td>/news/world-africa-68091775</td>\n",
       "      <td>Africa</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>Rolling Tuscan fields among stunning travel aw...</td>\n",
       "      <td>/news/in-pictures-68021767</td>\n",
       "      <td>In Pictures</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>Football fever and giant cake: Africa's top shots</td>\n",
       "      <td>/news/world-africa-67986204</td>\n",
       "      <td>Africa</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>Snowy scenes from around the UK</td>\n",
       "      <td>/weather/features/68006585</td>\n",
       "      <td>Features</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                title  \\\n",
       "0   UN in aid plea after staff accused of Israel a...   \n",
       "1         Protesters throw soup at Mona Lisa painting   \n",
       "2    World's largest cruise ship sets sail from Miami   \n",
       "3   Stokes hails 'greatest win' - reaction after E...   \n",
       "4   BBC confronts man who abused boy in secretive ...   \n",
       "5   Ukraine says it has uncovered major arms corru...   \n",
       "6   Who invented butter chicken? Creamy dish centr...   \n",
       "7                  Australian drill rap vs the police   \n",
       "8   Australian Open: Sinner beats Medvedev to win ...   \n",
       "9   FA Cup: Superb Neto opener gives Wolves lead a...   \n",
       "10      James edges out Curry as Lakers beat Warriors   \n",
       "11                The last male of an extinct species   \n",
       "12                    The cities cutting back on cars   \n",
       "13                    The plastic oceans we can't see   \n",
       "14             One of modern music's greatest enigmas   \n",
       "15    The curious ancient beginnings of 'bed culture'   \n",
       "16                    Is this curry's lighter cousin?   \n",
       "17  When employers gut middle managers, everyone h...   \n",
       "18         Your pictures on the theme of 'wilderness'   \n",
       "19     Beauty giant Avon under fire over Russia links   \n",
       "20  The Traitors TV final reaches dramatic conclusion   \n",
       "21      See what your brain does when you look at art   \n",
       "22  Why this US state abolished the death penalty ...   \n",
       "23             The secrets hidden in a reindeer brain   \n",
       "24  Auschwitz film was 'like Big Brother' in house...   \n",
       "25  Woodpeckers and sparrowhawks: Your Birdwatch 2...   \n",
       "26     Meta tool to block nude images in teens' chats   \n",
       "27   Alarming 45-fold rise in measles in Europe - WHO   \n",
       "28    Morrissey being treated for physical exhaustion   \n",
       "29  Mars crash ends Nasa helicopter Ingenuity's mi...   \n",
       "30      Golden age or dying days for British theatre?   \n",
       "31  Women take the lead in India’s Republic Day pa...   \n",
       "32  Bathers, wavers and semi-quavers: Africa's top...   \n",
       "33  Rolling Tuscan fields among stunning travel aw...   \n",
       "34  Football fever and giant cake: Africa's top shots   \n",
       "35                    Snowy scenes from around the UK   \n",
       "\n",
       "                                                 href                    tag  \\\n",
       "0                    /news/world-middle-east-68119268            Middle East   \n",
       "1                         /news/world-europe-68121654                 Europe   \n",
       "2                      /news/world-us-canada-68118822            US & Canada   \n",
       "3                        /sport/live/cricket/67780959                Cricket   \n",
       "4                      /news/world-us-canada-66449988            US & Canada   \n",
       "5                         /news/world-europe-68120973                 Europe   \n",
       "6                     /news/world-asia-india-68053470                  India   \n",
       "7                      /news/world-australia-67364463              Australia   \n",
       "8                         /sport/live/tennis/67779985                 Tennis   \n",
       "9                       /sport/live/football/68026390               Football   \n",
       "10                         /sport/basketball/68121154             Basketball   \n",
       "11  /future/article/20240124-the-photo-of-sudan-th...                    NaN   \n",
       "12  /future/article/20240122-from-london-to-new-yo...                    NaN   \n",
       "13  /future/article/20240115-visualising-the-great...                    NaN   \n",
       "14  https://www.bbc.com/culture/article/20240126-w...                Culture   \n",
       "15  https://www.bbc.com/future/article/20240126-sl...                 Future   \n",
       "16  https://www.bbc.com/travel/article/20240126-ke...                 Travel   \n",
       "17  https://www.bbc.com/worklife/article/20240126-...               Worklife   \n",
       "18      https://www.bbc.com/news/in-pictures-68082104            In Pictures   \n",
       "19         https://www.bbc.com/news/business-67425366               Business   \n",
       "20  https://www.bbc.com/news/entertainment-arts-68...   Entertainment & Arts   \n",
       "21  /reel/video/p0h6str5/see-what-your-brain-does-...                    NaN   \n",
       "22  /reel/video/p0h74jzx/why-this-us-state-abolish...                    NaN   \n",
       "23  /reel/video/p0h3t508/the-secrets-hidden-in-a-r...                    NaN   \n",
       "24                  /news/entertainment-arts-68016298   Entertainment & Arts   \n",
       "25                 /news/science-environment-68106504  Science & Environment   \n",
       "26                          /news/technology-68093343             Technology   \n",
       "27                              /news/health-68068226                 Health   \n",
       "28                  /news/entertainment-arts-68121824   Entertainment & Arts   \n",
       "29                 /news/science-environment-68099672  Science & Environment   \n",
       "30                  /news/entertainment-arts-68040691   Entertainment & Arts   \n",
       "31                    /news/world-asia-india-68091821                  India   \n",
       "32                        /news/world-africa-68091775                 Africa   \n",
       "33                         /news/in-pictures-68021767            In Pictures   \n",
       "34                        /news/world-africa-67986204                 Africa   \n",
       "35                         /weather/features/68006585               Features   \n",
       "\n",
       "                                              summary  \n",
       "0   Countries pause funding for UNRWA over Israeli...  \n",
       "1                                                 NaN  \n",
       "2                                                 NaN  \n",
       "3                                                 NaN  \n",
       "4                                                 NaN  \n",
       "5   Ukraine's security service accuses senior offi...  \n",
       "6   Butter chicken - a curry popular around the wo...  \n",
       "7   A standoff between a hip-hop act and law enfor...  \n",
       "8   Jannik Sinner beats Daniil Medvedev in the Aus...  \n",
       "9   Follow radio commentary and live text coverage...  \n",
       "10  LeBron James helps the Los Angeles Lakers to a...  \n",
       "11                                                NaN  \n",
       "12                                                NaN  \n",
       "13                                                NaN  \n",
       "14  How the elusive figure William Onyeabor became...  \n",
       "15  The ancient Romans had a different kind of bed...  \n",
       "16  This creamy and mild vegetarian dish a variati...  \n",
       "17  Companies are laying off experienced workers –...  \n",
       "18  A selection of striking images from our reader...  \n",
       "19  The firm is facing criticism for continuing pr...  \n",
       "20  Viewers found out in the final whether the tra...  \n",
       "21                                                NaN  \n",
       "22                                                NaN  \n",
       "23                                                NaN  \n",
       "24  For The Zone of Interest, hidden crews filmed ...  \n",
       "25                                                NaN  \n",
       "26                                                NaN  \n",
       "27                                                NaN  \n",
       "28                                                NaN  \n",
       "29                                                NaN  \n",
       "30                                                NaN  \n",
       "31                                                NaN  \n",
       "32                                                NaN  \n",
       "33                                                NaN  \n",
       "34                                                NaN  \n",
       "35                                                NaN  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.DataFrame(rows)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv(\"bbc-headlines.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
